/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AReceberRouteImport } from './routes/a-receber'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComprovantesRouteImport } from './routes/comprovantes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as UsuariosRouteImport } from './routes/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AReceberRoute = AReceberRouteImport.update({
  id: '/a-receber',
  path: '/a-receber',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprovantesRoute = ComprovantesRouteImport.update({
  id: '/comprovantes',
  path: '/comprovantes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-receber': typeof AReceberRoute
  '/auth': typeof AuthRoute
  '/comprovantes': typeof ComprovantesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/metas': typeof MetasRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-receber': typeof AReceberRoute
  '/auth': typeof AuthRoute
  '/comprovantes': typeof ComprovantesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/metas': typeof MetasRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-receber': typeof AReceberRoute
  '/auth': typeof AuthRoute
  '/comprovantes': typeof ComprovantesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/metas': typeof MetasRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-receber'
    | '/auth'
    | '/comprovantes'
    | '/configuracoes'
    | '/dashboard'
    | '/metas'
    | '/redefinir-senha'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-receber'
    | '/auth'
    | '/comprovantes'
    | '/configuracoes'
    | '/dashboard'
    | '/metas'
    | '/redefinir-senha'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/a-receber'
    | '/auth'
    | '/comprovantes'
    | '/configuracoes'
    | '/dashboard'
    | '/metas'
    | '/redefinir-senha'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AReceberRoute: typeof AReceberRoute
  AuthRoute: typeof AuthRoute
  ComprovantesRoute: typeof ComprovantesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  MetasRoute: typeof MetasRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-receber': {
      id: '/a-receber'
      path: '/a-receber'
      fullPath: '/a-receber'
      preLoaderRoute: typeof AReceberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprovantes': {
      id: '/comprovantes'
      path: '/comprovantes'
      fullPath: '/comprovantes'
      preLoaderRoute: typeof ComprovantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AReceberRoute: AReceberRoute,
  AuthRoute: AuthRoute,
  ComprovantesRoute: ComprovantesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  MetasRoute: MetasRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
